# Generated by Django 5.0 on 2024-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_alter_review_email_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10, null=True),
        ),
    ]
